In [1]:
import pandas as pd
df=pd.read_csv("Data1.csv")
df.head(10)

,Unnamed: 0,Unnamed: 1,Cultivar ID,Sequences,Plant Height(cm),Subpopulation,Yield
0,0,0,W128,ACCGATCTT,149.8,Intermediate,46.26
1,1,0,W030,GCCGTACTT,172.6,Indica Intermediate,42.82
2,2,0,W049,GCCGTACTC,163.8,Aus,25.26
3,2,1,W134,GCCGTACTC,150.0,Aus,49.84
4,3,0,W256,GCCGTACCC,160.0,VI/Aromatic,28.73
5,3,1,W081,GCCGTACCC,130.2,VI/Aromatic,19.74
6,4,0,W028,GTCGTTCTC,164.2,Aus,29.82
7,5,0,W099,GCCGTTCTC,149.0,Aus,39.03
8,5,1,W287,GCCGTTCTC,150.2,Aus,40.88
9,5,2,W115,GCCGTTCTC,153.4,Aus,40.41

In [2]:
del df["Unnamed: 1"]

In [3]:
df = df.rename(columns={'Unnamed: 0': 'index'})

In [4]:
df

,index,Cultivar ID,Sequences,Plant Height(cm),Subpopulation,Yield
0,0,W128,ACCGATCTT,149.80,Intermediate,46.26
1,1,W030,GCCGTACTT,172.60,Indica Intermediate,42.82
2,2,W049,GCCGTACTC,163.80,Aus,25.26
3,2,W134,GCCGTACTC,150.00,Aus,49.84
4,3,W256,GCCGTACCC,160.00,VI/Aromatic,28.73
...,...,...,...,...,...,...
524,67,C099,GCTGTTTTC,176.80,Indica Intermediate,18.19
525,67,W033,GCTGTTTTC,155.00,Indica I,25.69
526,67,W192,GCTGTTTTC,121.20,Intermediate,36.02
527,67,C066,GCTGTTTTC,120.27,Indica I,22.28
528,67,W107,GCTGTTTTC,163.20,Indica Intermediate,27.58

In [5]:
from statistics import mean,median,mode

In [6]:

plhh=[]
for i in range(68):
    count=0
    plh=[]
    a=[]
    for j in range(len(df["Plant Height(cm)"])):
        if(df["index"][j]==i):
            #print(df.loc[j])
            plh.append(df["Plant Height(cm)"][j])
    c=mean(plh)
    for i in range(len(plh)):
        plhh.append(c)

In [7]:
df["Plant Height(cm)"]=plhh

In [9]:

subpop=[]
plhh=[]
for i in range(68):
    count=0
    sbp=[]
    plh=[]
    for j in range(len(df["index"])):
        if(df["index"][j]==i):
            #print(df.loc[j])
            sbp.append(df["Subpopulation"][j])
    print(sbp)
    if(len(sbp)==2):sbp[1]=sbp[0]
    else:
        a=len(sbp)
        b=mode(sbp)
        for i in range(a):sbp[i]=b
    for i in sbp:
        subpop.append(i)
    #print(sbp)

['Intermediate']
['Indica Intermediate']
['Aus', 'Aus']
['VI/Aromatic', 'VI/Aromatic']
['Aus']
['Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Indica Intermediate', 'Aus', 'Aus', 'Aus']
['Aus', 'Intermediate']
['Indica I', 'Indica I', 'Indica I', 'Indica I']
['Indica Intermediate', 'Indica III', 'Indica III', 'Indica II', 'Indica III']
['VI/Aromatic']
['VI/Aromatic', 'Aus', 'Aus', 'Aus', 'Aus', 'VI/Aromatic', 'Aus', 'VI/Aromatic']
['Aus', 'Aus']
['Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Aus', 'Indica Intermediate', 'Aus', 'Aus', 'Aus', 'Aus']
['Indica III', 'Indica I']
['Indica Intermediate', 'Indica Intermediate', 'Indica I', 'Indica III', 'Indica I', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica Intermediate', 'Indica I', 'Indica III']
['Indica I']
['Indica I', 'Indica Intermediate', 'Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica Intermediate']
['Indica Intermediate']
['Indica Intermediate', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica I', 'Indica I']
['Japonica Intermediate']
['Indica I', 'Indica I']
['VI/Aromatic']
['VI/Aromatic', 'VI/Aromatic', 'Aus', 'VI/Aromatic', 'Aus', 'VI/Aromatic', 'Aus']
['Indica I']
['Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica I']
['Indica Intermediate']
['Aus', 'VI/Aromatic', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Aus', 'Indica Intermediate']
['Indica Intermediate', 'Indica Intermediate', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica I', 'Indica I']
['Indica I', 'Indica I', 'Indica III', 'Indica II', 'Indica Intermediate']
['VI/Aromatic']
['VI/Aromatic', 'Japonica Intermediate', 'Japonica Intermediate']
['Indica I', 'Intermediate']
['Indica Intermediate', 'Indica Intermediate']
['Indica Intermediate', 'Indica II', 'Indica III', 'Indica II', 'Indica II', 'Indica Intermediate', 'Intermediate']
['Indica Intermediate', 'Indica II', 'Indica III', 'Indica I', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica I', 'Indica III']
['Indica I', 'Indica I', 'Indica Intermediate']
['Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica II', 'Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica I']
['Indica Intermediate', 'Indica Intermediate', 'Indica I']
['Indica I', 'Indica I', 'Indica I', 'Indica I', 'Indica I']
['Indica Intermediate', 'Indica I']
['Indica I', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica III', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica I']
['Japonica Intermediate', 'Temperate Japonica', 'Temperate Japonica']
['Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica']
['Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica']
['Japonica Intermediate', 'Temperate Japonica', 'Japonica Intermediate', 'Temperate Japonica', 'Japonica Intermediate', 'Tropical Japonica']
['Japonica Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Japonica Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Japonica Intermediate', 'Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Japonica Intermediate', 'Temperate Japonica', 'Japonica Intermediate']
['Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Tropical Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica']
['Indica Intermediate', 'Intermediate']
['Japonica Intermediate', 'Japonica Intermediate', 'Temperate Japonica', 'Japonica Intermediate', 'Japonica Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Japonica Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica']
['Temperate Japonica', 'Intermediate', 'Indica I', 'Temperate Japonica', 'Japonica Intermediate', 'Temperate Japonica']
['Tropical Japonica']
['Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica']
['Temperate Japonica', 'Tropical Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Intermediate', 'Temperate Japonica', 'Tropical Japonica']
['Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Temperate Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica']
['Temperate Japonica', 'Tropical Japonica', 'Tropical Japonica']
['Indica II', 'Indica I', 'Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Temperate Japonica']
['Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica I', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica I', 'Indica II', 'Indica II', 'Indica I', 'Indica Intermediate', 'Indica II', 'Indica II', 'Tropical Japonica', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica I', 'Indica Intermediate', 'Indica I', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica I', 'Indica II', 'Indica Intermediate', 'Indica II', 'Intermediate', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica II', 'Indica I', 'Indica II', 'Indica III', 'Indica II', 'Indica Intermediate', 'Indica I', 'Indica II', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica Intermediate']
['Temperate Japonica']
['Indica I', 'Indica I', 'Indica Intermediate']
['Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica']
['Temperate Japonica', 'Temperate Japonica', 'Japonica Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Tropical Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Temperate Japonica', 'Tropical Japonica', 'Indica Intermediate', 'Indica Intermediate', 'Temperate Japonica', 'Temperate Japonica', 'Japonica Intermediate', 'Tropical Japonica', 'Tropical Japonica', 'Temperate Japonica', 'Indica II']
['Indica III', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica I']
['Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica II', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica I', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica I', 'Indica II', 'Indica Intermediate', 'Indica I', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica I', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica I', 'Indica I', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica II', 'Indica II', 'Indica II', 'Indica Intermediate', 'Indica II', 'Indica II', 'Indica II', 'Indica II', 'Tropical Japonica', 'Tropical Japonica', 'Indica II', 'Indica II', 'Indica II']
['Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica']
['Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica', 'Tropical Japonica']
['Indica Intermediate']
['Tropical Japonica', 'Indica II', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Indica Intermediate', 'Tropical Japonica', 'Indica Intermediate']
['Intermediate', 'Indica Intermediate', 'Indica I', 'Intermediate', 'Indica I', 'Indica Intermediate']

In [10]:
leg={'A':'1','C':'3','G':'4','T':'4'}
seqq=[]
for i in df['Sequences']:
    seq=""
    for j in i:seq+=leg[j]
    seqq.append(int(seq))

In [11]:
df["Sequences"]=seqq
df["Subpopulation"]=subpop

In [12]:
df

,index,Cultivar ID,Sequences,Plant Height(cm),Subpopulation,Yield
0,0,W128,133414344,149.800000,Intermediate,46.26
1,1,W030,433441344,172.600000,Indica Intermediate,42.82
2,2,W049,433441343,156.900000,Aus,25.26
3,2,W134,433441343,156.900000,Aus,49.84
4,3,W256,433441333,145.100000,VI/Aromatic,28.73
...,...,...,...,...,...,...
524,67,C099,434444443,142.911667,Intermediate,18.19
525,67,W033,434444443,142.911667,Intermediate,25.69
526,67,W192,434444443,142.911667,Intermediate,36.02
527,67,C066,434444443,142.911667,Intermediate,22.28
528,67,W107,434444443,142.911667,Intermediate,27.58

In [13]:
del df["index"]
df.to_csv("Encodseqdf.csv")

MACHINE LEARNING PART

In [14]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [15]:
df1=pd.read_csv("Encodseqdf.csv")

In [16]:
df1

,Unnamed: 0,Cultivar ID,Sequences,Plant Height(cm),Subpopulation,Yield
0,0,W128,133414344,149.800000,Intermediate,46.26
1,1,W030,433441344,172.600000,Indica Intermediate,42.82
2,2,W049,433441343,156.900000,Aus,25.26
3,3,W134,433441343,156.900000,Aus,49.84
4,4,W256,433441333,145.100000,VI/Aromatic,28.73
...,...,...,...,...,...,...
524,524,C099,434444443,142.911667,Intermediate,18.19
525,525,W033,434444443,142.911667,Intermediate,25.69
526,526,W192,434444443,142.911667,Intermediate,36.02
527,527,C066,434444443,142.911667,Intermediate,22.28
528,528,W107,434444443,142.911667,Intermediate,27.58

In [17]:
x1=df['Sequences'].values
y1=df['Subpopulation'].values

In [18]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(x1, y1, test_size=0.20, random_state=42)
x_train1 = x_train1.reshape(-1, 1)
x_test1 = x_test1.reshape(-1, 1)

In [19]:
subpoprf = KNeighborsClassifier()  # Corrected class name
subpoprf.fit(x_train1, y_train1)
y_pred1 = subpoprf.predict(x_test1)
y_pred1

array(['Temperate Japonica', 'Indica II', 'Indica Intermediate',
       'Temperate Japonica', 'Tropical Japonica', 'Indica I',
       'Temperate Japonica', 'Indica II', 'Indica Intermediate',
       'Indica I', 'Aus', 'Intermediate', 'Indica I',
       'Temperate Japonica', 'Tropical Japonica', 'Indica II',
       'Indica Intermediate', 'Indica II', 'Temperate Japonica',
       'Temperate Japonica', 'Indica Intermediate', 'Indica II',
       'Indica I', 'Indica II', 'Indica II', 'Indica Intermediate',
       'Indica I', 'Indica I', 'Indica Intermediate',
       'Temperate Japonica', 'Indica I', 'Aus', 'Indica II', 'Indica II',
       'Indica I', 'Indica I', 'Indica II', 'Indica I', 'Aus',
       'Japonica Intermediate', 'Indica I', 'Indica II',
       'Temperate Japonica', 'Indica Intermediate', 'Indica II',
       'Tropical Japonica', 'Temperate Japonica', 'Temperate Japonica',
       'Indica I', 'Indica I', 'Intermediate', 'Temperate Japonica',
       'Indica II', 'Indica I', 'Indica II', 'Temperate Japonica',
       'Indica II', 'Indica I', 'Indica II', 'Indica II',
       'Temperate Japonica', 'Indica Intermediate', 'Indica II',
       'Temperate Japonica', 'Indica I', 'Temperate Japonica',
       'Indica II', 'Indica I', 'Indica I', 'Temperate Japonica',
       'Indica I', 'Indica II', 'Temperate Japonica', 'Indica I',
       'Intermediate', 'Indica I', 'Indica I', 'Indica I',
       'Temperate Japonica', 'Aus', 'Indica II', 'Aus',
       'Temperate Japonica', 'Temperate Japonica', 'Indica II',
       'Indica II', 'Indica I', 'Indica Intermediate', 'Aus', 'Indica II',
       'Indica I', 'Aus', 'Temperate Japonica', 'VI/Aromatic',
       'Indica II', 'Aus', 'Indica I', 'Tropical Japonica', 'Indica I',
       'Indica I', 'Indica II', 'Indica II', 'Indica II', 'Indica I',
       'Indica II', 'Tropical Japonica'], dtype=object)

In [20]:
subpopac=accuracy_score(y_test1,y_pred1)
subpopac

0.8773584905660378

In [21]:

x2 = df['Sequences'].values
y2 = df['Plant Height(cm)'].values
x_train2, x_test2, y_train2, y_test2 = train_test_split(x2, y2, test_size=0.25)
x_test2 = x_test2.reshape(-1, 1)
x_train2 = x_train2.reshape(-1, 1)
plhrf = RandomForestRegressor(n_estimators=100,random_state=35,max_depth=10)
plhrf.fit(x_train2, y_train2)
y_pred2 = plhrf.predict(x_test2)
y_pred2

array([134.66938705, 163.88421443, 109.38648249, 109.38648249,
       154.73249033, 163.96043067, 166.57941491,  89.77438991,
       154.73249033, 109.38648249, 148.28090892, 163.88421443,
       109.38648249, 109.38648249, 109.38648249, 109.38648249,
       109.38648249, 109.38648249, 109.38648249, 109.38648249,
       109.38648249, 109.38648249, 148.28090892, 109.38648249,
       109.38648249, 166.57941491, 133.71004222, 103.6934817 ,
       146.63789678, 163.88421443, 134.66938705, 163.96043067,
       163.96043067, 109.38648249, 133.71004222, 133.71004222,
       163.96043067, 163.96043067, 154.73249033, 133.71004222,
       133.71004222, 103.6934817 , 109.38648249, 103.6934817 ,
       148.28090892, 133.71004222, 163.96043067, 164.52043971,
       103.6934817 , 103.6934817 , 109.38648249, 146.63789678,
       103.6934817 , 133.71004222, 154.11050615, 162.06958793,
       133.71004222, 109.38648249, 163.96043067, 109.38648249,
       109.38648249, 133.71004222, 109.38648249, 166.57941491,
       166.57941491, 109.38648249, 154.11050615, 134.66938705,
       154.73249033, 146.63789678, 133.71004222,  89.77438991,
       163.96043067, 163.96043067, 103.6934817 , 134.66938705,
       121.86853766, 109.38648249, 146.63789678, 109.38648249,
       163.96043067, 103.6934817 , 109.38648249, 109.38648249,
       109.38648249, 109.38648249, 109.38648249, 154.73249033,
       146.63789678, 148.28090892, 109.38648249, 133.71004222,
       109.38648249, 154.73249033, 154.73249033, 109.38648249,
       134.66938705, 163.88421443, 109.38648249, 109.38648249,
       134.66938705, 154.73249033, 109.38648249, 163.96043067,
       109.38648249, 154.73249033, 109.38648249, 133.71004222,
       148.28090892, 154.73249033, 109.38648249, 154.73249033,
       163.96043067, 134.66938705, 105.58340185, 109.38648249,
       133.71004222, 133.71004222, 133.71004222, 164.52043971,
       134.66938705, 109.38648249, 103.6934817 , 109.38648249,
       148.28090892, 163.96043067, 163.96043067, 163.88421443,
       148.28090892,  89.77438991,  89.77438991, 134.66938705,
       154.73249033])

In [22]:
heightacc=r2_score(y_test2,y_pred2)
heightacc

0.7943493225425913

In [23]:

x3 = df['Sequences'].values
y3 = df['Yield'].values
x_train3, x_test3, y_train3, y_test3 = train_test_split(x2, y2, test_size=0.25)
x_test3 = x_test3.reshape(-1, 1)
x_train3 = x_train3.reshape(-1, 1)
yld = RandomForestRegressor()
yld.fit(x_train3, y_train3)
y_pred3 = yld.predict(x_test3)
ylac=r2_score(y_test3,y_pred3)
ylac

0.7875339936114923

In [24]:
a = input("Enter a 9 digit sequence: ")
leg = {'A': '1', 'C': '3', 'G': '4', 'T': '4'}
seqq = ""
for j in a:
    seqq += leg[j]
score = np.array([int(seqq)])  # Convert the sequence to an integer array
score = score.reshape(-1, 1)
prh = plhrf.predict(score)
sbpp = subpoprf.predict(score)
yeils=yld.predict(score)
print("Entered sequence: ", a)
print("Predicted height: ", prh[0])
print("Accuracy for the height: ",heightacc*100,"%")
print("Predicted subpopulation: ", sbpp[0])
print("Accuracy of the subpopulation :",subpopac*100,"%")
print("Predicted Yield:",yeils[0])
print("Accuracy of Yield: ",ylac*100,"%")

Entered sequence:  ACTACTAAG
Predicted height:  105.58340185185182
Accuracy for the height:  79.43493225425912 %
Predicted subpopulation:  Temperate Japonica
Accuracy of the subpopulation : 87.73584905660378 %
Predicted Yield: 104.67536388888885
Accuracy of Yield:  78.75339936114923 %

In [ ]:
import pickle 
with open('datasubpopulation.pkl','wb') as f:
    pickle.dump(subpoprf,f)

with open('dataheight.pkl','wb') as f1:
    pickle.dump(plhrf,f1)

with open('datayield.pkl','wb') as f2:
    pickle.dump(yld,f2)